stages:
  - build
  - test
  - deploy

# Build stage - pour installer les dépendances
build:
  stage: build
  image: node:20  # Utilisation de Node.js 20
  script:
    - echo "Installation des dépendances"
    - npm install  # Installe toutes les dépendances, y compris les devDependencies
  cache:
    paths:
      - node_modules/

# Test stage - pour exécuter les tests unitaires et d'intégration
test:
  stage: test
  image: node:20  # Utilisation de Node.js 20
  script:
    - echo "Installation des dépendances"
    - npm install  # Assure que toutes les dépendances, y compris les devDependencies, sont installées
  only:
    - main  # Cette étape ne s'exécute que sur la branche principale

# Deploy stage - pour déployer l'application
deploy:
  stage: deploy
  image: node:20  # Utilisation de Node.js 20 pour le déploiement
  script:
    - echo "Installation des dépendances"
    - npm install
    - echo "Démarrage de l'application"
    - npm start  # Démarre l'application avec "npm start"
  only:
    - main  # Cette étape ne s'exécute que sur la branche principale

# Variables d'environnement
variables:
  NODE_ENV: "production"
