stages:
  - build
  - test
  - deploy

# Build stage - pour installer les dépendances (par exemple, avec npm si c'est une app Node.js)
build:
  stage: build
  script:
    - echo "Installation des dépendances"
    - npm install
  cache:
    paths:
      - node_modules/

# Test stage - pour exécuter les tests de l'application (si vous en avez)
test:
  stage: test
  script:
    - echo "Exécution des tests"
    - npm test
  only:
    - main

# Deploy stage - pour déployer votre application sur un serveur distant (Heroku, AWS, etc.)
deploy:
  stage: deploy
  script:
    - echo "Déploiement de l'application"
    - npm run deploy # Si vous avez un script pour déployer, par exemple vers un serveur ou une plateforme cloud
  only:
    - main

# Vous pouvez également configurer des variables d'environnement sensibles (API keys, etc.)
variables:
  NODE_ENV: "production"
