stages:
  - build
  - test
  - deploy

# Build stage - pour installer les dépendances
build:
  stage: build
  image: node:18  # Mise à jour pour Node.js 18
  script:
    - echo "Installation des dépendances"
    - npm install
  cache:
    paths:
      - node_modules/

# Test stage - pour exécuter les tests de l'application (unitaires et d'intégration)
test:
  stage: test
  image: node:16  # Version Node.js 16
  script:
    - echo "Installation des dépendances "
    - npm install # Assurez-vous que toutes les dépendances, y compris mocha, sont installées
    - npm install -g mocha # Installation globale de mocha
    - echo "Exécution des tests unitaires"
    - mocha --parallel false --timeout 30000 'test/models/*.test.js'
    - echo "Exécution des tests d'intégration"
    - npm run integration-test
  only:
    - main


# Deploy stage - pour déployer l'application
deploy:
  stage: deploy
  image: node:18  # Mise à jour pour Node.js 18
  script:
    - echo "Démarrage de l'application"
    - npm start
  only:
    - main

# Variables d'environnement
variables:
  NODE_ENV: "production"
