stages:
  - build
  - test
  - deploy

# Build stage - pour installer les dépendances
build:
  stage: build
  image: node:16 # Utilisation de l'image Node.js officielle
  script:
    - echo "Installation des dépendances"
    - npm install
  cache:
    paths:
      - node_modules/

# Test stage - pour exécuter les tests de l'application (unitaires et d'intégration)
test:
  stage: test
  image: node:16 # Utilisation de l'image Node.js officielle
  script:
    - echo "Exécution des tests unitaires"
    - npm run unit-test
    - echo "Exécution des tests d'intégration"
    - npm run integration-test
  only:
    - main

# Deploy stage - pour déployer l'application
deploy:
  stage: deploy
  image: node:16 # Utilisation de l'image Node.js officielle
  script:
    - echo "Démarrage de l'application"
    - npm start
  only:
    - main

# Variables d'environnement
variables:
  NODE_ENV: "production"
